version: '3.2'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "127.0.0.1:33306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_backup:/mysql_backup
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
